import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="w-full bg-gray-100 dark:bg-gray-900 py-4 shadow">
          <nav className="container mx-auto flex gap-4 justify-center">
            <a href="/" className="font-medium hover:underline">Home</a>
            <a href="/create-account" className="font-medium hover:underline">Create Account</a>
            <a href="/sell-product" className="font-medium hover:underline">Sell Product</a>
            <a href="/search" className="font-medium hover:underline">Search Product</a>
            <a href="/buy" className="font-medium hover:underline">Buy Product</a>
            <a href="/dashboard" className="font-medium hover:underline">Dashboard</a>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
